spring.application.name=PRJWebService
server.port=8080

spring.datasource.url=jdbc:h2:mem:prjwebservice;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

app.jwt.secret=prjwebservice-prjwebservice-prjwebservice-secret-key-2026
app.jwt.expiration-minutes=30
